micronaut:
  application:
    name: watch
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
              base64: true
              jws-algorithm: HS256
  server:
    port: 8081
    netty:
      access-logger:
        enabled: true
        log-format: common
    max-request-size: 4GB
    multipart:
      max-file-size: 4GB
grpc:
  client:
    max-retry-attempts: 10
  channels:
    mailer:
      for-address: ${MAILER_GRPC_HOST:127.0.0.1}:${MAILER_GRPC_PORT:50011}
      plaintext: true
      max-retry-attempts: 10
netty:
  default:
    allocator:
      max-order: 3
cassandra:
  default:
    advanced:
      ssl: false
      ssl-engine-factory: DefaultSslEngineFactory
      metadata:
        schema:
          enabled: true
    basic:
      contact-points:
        - ${CASSANDRA_HOST:127.0.0.1}:${CASSANDRA_PORT:9042}
      load-balancing-policy:
        local-datacenter: ${CASSANDRA_DATA_CENTER:datacenter1}
      session-keyspace: app
blob:
  cloud-name: azure
azure:
  blob:
    endpoint: ${AZURE_BLOB_ENDPOINT:localhost}
